set pagesize 100
set linesize 400
select 
CAST(SYS_CONTEXT('USERENV','SERVER_HOST') as VARCHAR2(15)) as "HOST"
,CAST(SYS_CONTEXT('USERENV','DB_NAME') as VARCHAR2(10)) as "DBNAME"
,CAST(SYS_CONTEXT('USERENV','INSTANCE') as VARCHAR2(4)) as "INST"
,CAST(OWNER AS VARCHAR2(12)) as OWNER
,CAST(DIRECTORY_NAME AS VARCHAR2(40)) as DIRECTORY_NAME
,CAST(DIRECTORY_PATH AS VARCHAR2(90)) as PATH from dba_directories where DIRECTORY_NAME like '%OCM_CONFIG%';
