CREATE ROLE ROLE_JDE_WS_RO;



create user JDE_WS_RO identified by "U2Band" ACCOUNT UNLOCK;
alter user JDE_WS_RO profile "APP_NO_EXPIRE_PW";
grant connect to JDE_WS_RO;
GRANT ROLE_JDE_WS_RO TO JDE_WS_RO;


-- jdeprod
--GRANT SELECT ON PRODDTA.F06146 TO ROLE_JDE_WS_RO;
--jdedev
--GRANT SELECT ON TESTDTA.F06146 TO ROLE_JDE_WS_RO;
--jdetest
--GRANT SELECT ON CRPDTA.F06146 TO ROLE_JDE_WS_RO;


