-- EPC SQL Create User
CREATE SMALLFILE TABLESPACE "__UN__" 
  DATAFILE SIZE 144M AUTOEXTEND ON NEXT 144M MAXSIZE 576M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT 
  NOCOMPRESS SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER "__UN__" IDENTIFIED BY "__PW__"
      DEFAULT TABLESPACE "__UN__"
      TEMPORARY TABLESPACE "TEMP"
      PROFILE "APP_NO_EXPIRE_PW";

GRANT CONNECT TO __UN__;
GRANT RESOURCE TO __UN__;
GRANT CREATE DATABASE LINK TO __UN__;
GRANT CREATE VIEW TO __UN__;
GRANT UNLIMITED TABLESPACE TO __UN__;
GRANT SELECT_CATALOG_ROLE TO __UN__;

