--swo 
CREATE SMALLFILE TABLESPACE "DEV_ASRLIST"
        DATAFILE '+DATA_XA02'
        SIZE 144M AUTOEXTEND ON NEXT 144M
        MAXSIZE 16G LOGGINGEXTENT
        MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;

