-- cloned from DEV_ASRPERMITS   swo

CREATE USER "DEV_ASRLIST"
        PROFILE "APP_NO_EXPIRE_PW" IDENTIFIED BY "*******"
        DEFAULT TABLESPACE "DEV_ASRLIST"
        TEMPORARY TABLESPACE "TEMP"
        ACCOUNT UNLOCK;

GRANT CREATE DATABASE LINK TO "DEV_ASRLIST";
GRANT CREATE VIEW TO "DEV_ASRLIST";
GRANT UNLIMITED TABLESPACE TO "DEV_ASRLIST";
GRANT "CONNECT" TO "DEV_ASRLIST";
GRANT "DEV_ASRPERMITS_ALL_DML_ROLE" TO "DEV_ASRLIST";
GRANT "QRY_ANALYSIS_ROLE" TO "DEV_ASRLIST";
GRANT "RESOURCE" TO "DEV_ASRLIST";

