
An account has been created for you on 
one of the company Oracle databases in
support of the following application:

Application: <<APPLICATION>>

The information you need to logon to this
database is as follows:

Username   : <<USERNAME>>
Password   : <<PASSWORD>>
Database   : <<DATABASE>>

Grants     : <<PRIVS>>
Quotas     : <<QUOTAS>>

If you are unsure why you received this email
or are having difficulty, please contact the
Help Desk at 555-346-2852.

Thank You,
Your DBA Team

