#!/bin/bash
####################################
function bytesToHuman {
SLIST="bytes,KB,MB,GB,TB,PB,EB,ZB,YB"
    POWER=1
    VAL=$( echo "scale=2; $SIZE / 1" | bc)
    VINT=$( echo $VAL / 1024 | bc )
    while [ $VINT -gt 0 ]
    do
        let POWER=POWER+1
        VAL=$( echo "scale=2; $VAL / 1024" | bc)
        VINT=$( echo $VAL / 1024 | bc )
    done

    echo $VAL$( echo $SLIST | cut -f$POWER -d, )
}
####################################
function collectHostsFromFile {
HOSTLIST=$(cat $1 | cut -s -d'|' -f1 |  tr '\r\n' ' ')
echo ${HOSTLIST}
}
####################################
function fileExists {
# return 0 if found
if [[  -f "${1}" ]]; then
echo 0
else
echo 1
fi
}
####################################
function assertIdentityFile {
if [[ -z "${ORCL_SSHIDFILE}" ]]; then
    print "Identity File environment variable ORCL_SSHIDFILE not defined"
    exit 1
fi
if [[ ! -f "${ORCL_SSHIDFILE}" ]]; then
    printf "Identity File not found: %s\n" "${ORCL_SSHIDFILE}"
    exit 1
fi
}
####################################
