set feedback off
set pagesize 9999
set linesize 9999
column USERNAME format A20
column ACCOUNT_STATUS format A20
column PROFILE format A20
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT ='MM/DD/YYYY HH24:MI:SS TZR TZD';
ALTER SESSION SET NLS_DATE_FORMAT ='MM-DD-YYYY HH24:MI:SS';

-- accounts expiring in 7 days
select 
SYSDATE as CURRENT_DT
,CAST(SYS_CONTEXT('USERENV','SERVER_HOST') as VARCHAR2(15)) as "HOST"
,CAST(SYS_CONTEXT('USERENV','DB_NAME') as VARCHAR2(10)) as "DBNAME"
,USERNAME, ACCOUNT_STATUS, LOCK_DATE, EXPIRY_DATE
from DBA_USERS
where 
EXPIRY_DATE < SYSDATE + 7
AND
LOCK_DATE IS NULL
order by username asc;

select 
SYSDATE as CURRENT_DT
,CAST(SYS_CONTEXT('USERENV','SERVER_HOST') as VARCHAR2(15)) as "HOST"
,CAST(SYS_CONTEXT('USERENV','DB_NAME') as VARCHAR2(10)) as "DBNAME"
,USERNAME, ACCOUNT_STATUS, LOCK_DATE, EXPIRY_DATE, PROFILE 
from DBA_USERS
order by username asc;

