
-- set long 20000 longchunksize 20000 pagesize 0 linesize 1000 feedback off verify off trimspool on
-- column ddl format a3000
-- SELECT DBMS_METADATA.GET_DDL('PROFILE','APP_NO_EXPIRE_PW') as ddl FROM DUAL;



 CREATE PROFILE "APP_NO_EXPIRE_PW"
    LIMIT
	 COMPOSITE_LIMIT UNLIMITED
	 SESSIONS_PER_USER UNLIMITED
	 CPU_PER_SESSION UNLIMITED
	 CPU_PER_CALL UNLIMITED
	 LOGICAL_READS_PER_SESSION UNLIMITED
	 LOGICAL_READS_PER_CALL UNLIMITED
	 IDLE_TIME UNLIMITED
	 CONNECT_TIME UNLIMITED
	 PRIVATE_SGA UNLIMITED
	 FAILED_LOGIN_ATTEMPTS 10
	 PASSWORD_LIFE_TIME UNLIMITED
	 PASSWORD_REUSE_TIME UNLIMITED
	 PASSWORD_REUSE_MAX UNLIMITED
	 PASSWORD_VERIFY_FUNCTION NULL
	 PASSWORD_LOCK_TIME 86400/86400
	 PASSWORD_GRACE_TIME 604800/86400
;

-- SELECT DBMS_METADATA.GET_DDL('USER','PROD_APPMETADATA') as ddl from dual;

CREATE USER "PROD_APPMETADATA" IDENTIFIED BY 'password'
      DEFAULT TABLESPACE "PROD_APPMETADATA"
      TEMPORARY TABLESPACE "TEMP"
      PROFILE "APP_NO_EXPIRE_PW"
;

CREATE USER "PROD_ASRPERMITS" IDENTIFIED BY 'password'
      DEFAULT TABLESPACE "PROD_ASRPERMITS"
      TEMPORARY TABLESPACE "TEMP"
      PROFILE "APP_NO_EXPIRE_PW"
;

CREATE USER "PROD_ASRLIST" IDENTIFIED BY 'password'
      DEFAULT TABLESPACE "PROD_ASRLIST"
      TEMPORARY TABLESPACE "TEMP"
      PROFILE "APP_NO_EXPIRE_PW"
;
