SELECT Q.SQL_ID, Q.INST_ID, S.USERNAME, Q.elapsed_time, S.SID, S.SERIAL#, S.STATUS 
, Q.SQL_TEXT
FROM  GV$SQL Q LEFT OUTER JOIN GV$SESSION S
ON Q.SQL_ID = S.SQL_ID
WHERE 
-- S.USERNAME IS NOT NULL
--AND S.STATUS = 'ACTIVE'
--AND S.SQL_ID IS NOT NULL
Q.sql_id like '%vr24%'
;
