set pagesize 99
set linesize 220
set feedback off
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT ='MM/DD/YYYY HH24:MI:SS TZR TZD';
ALTER SESSION SET NLS_DATE_FORMAT ='MM-DD-YYYY HH24:MI:SS';
with base as
(
select 
CAST(SYS_CONTEXT('USERENV','SERVER_HOST') as VARCHAR2(15)) as "HOST"
,CAST(SYS_CONTEXT('USERENV','DB_NAME') as VARCHAR2(10)) as "DBNAME"
,CAST(inst_id as VARCHAR2(10)) as "INST_ID"
,CAST(SYS_CONTEXT('USERENV','INSTANCE') as VARCHAR2(4)) as "INST"
,CAST(to_char(startup_time,'DD-MON-YYYY HH24:MI:SS') as VARCHAR2(20)) as "STARTTIME"
,CAST((sysdate - startup_time)*24*60 as varchar2(12)) as  "UPTIME MINUTES"
,CAST(SYS_CONTEXT('USERENV','CURRENT_SCHEMA') as VARCHAR(15)) as "USER"
,CAST(SYS_CONTEXT('USERENV','SERVICE_NAME') as VARCHAR2(20)) as "SERVICE_NAME"
,CAST(to_char(sysdate,'DD-MON-YYYY HH24:MI:SS') as VARCHAR2(20)) as "CURRENTDT"
from gv$instance
)
select HOST,INST_ID,DBNAME,SERVICE_NAME,CURRENTDT,"USER",STARTTIME
,CAST(TRUNC ("UPTIME MINUTES" / 60) || ' Hours, ' || TRUNC(MOD("UPTIME MINUTES",  60)) || ' Minutes' as varchar(30)) AS UPTIME
from base;

