set pagesize 99
set linesize 132
select CAST(SYS_CONTEXT('USERENV','CURRENT_SCHEMA') as VARCHAR(15)) as "USER",CAST(SYS_CONTEXT('USERENV','SERVER_HOST') as VARCHAR2(15)) as "HOST",
CAST(SYS_CONTEXT('USERENV','SERVICE_NAME') as VARCHAR2(20)) as "SERVICE_NAME",
CAST(SYS_CONTEXT('USERENV','DB_NAME') as VARCHAR2(10)) as "DBNAME",
CAST(SYS_CONTEXT('USERENV','INSTANCE') as VARCHAR2(4)) as "INST" from dual;

